name: Create Artifact

on: 
  pull_request:
    branches:
      - main
  
env:
  DOTNET_VERSION: '8.0.203'

jobs:
  build_and_test:
    name: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish Linux
      run: dotnet publish --configuration Release --no-restore -r linux-x64 -p:PublishSingleFile=true --self-contained --output ./publish-linux

    - name: Publish Windows
      run: dotnet publish --configuration Release --no-restore -r win-x64 -p:PublishSingleFile=true --self-contained --output ./publish-win

    - name: Publish Linux Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mimic-linux-artifact
        path: ./publish-linux
        
    - name: Publish Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mimic-windows-artifact
        path: ./publish-windows